name: Deploy to AWS ECS Fargate

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Se connecter à AWS via les secrets IAM
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Login à ECR (automatique)
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Build Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.ECR_REPOSITORY }} .

    # 5. Tag Docker pour ECR
    - name: Tag Docker image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    # 6. Push Docker dans ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    # 7. Générer une nouvelle Task Definition ECS avec la nouvelle image
    - name: Render Amazon ECS task definition
      id: taskdef
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task.json
        container-name: ecs-nodejs-container
        image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    # 8. Déployer dans ECS Fargate
    - name: Deploy to Amazon ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.taskdef.outputs.task-definition }}
        cluster: ${{ secrets.ECS_CLUSTER }}
        service: ${{ secrets.ECS_SERVICE }}
        wait-for-service-stability: true
